=== PrairieLearn/PrairieLearn/schemas/schemas/infoCourse.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Course information",
    "description": "The specification file for a course.",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "uuid",
        "name",
        "title",
        "topics"
    ],
    "properties": {
        "comment": {
            "description": "Arbitrary comment for reference purposes.",
            "anyOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}]
        },
        "uuid": {
            "description": "Unique identifier (UUID v4).",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "name": {
            "description": "The course name (e.g., 'TAM 212').",
            "type": "string"
        },
        "title": {
            "description": "The course title (e.g., 'Introductory Dynamics').",
            "type": "string"
        },
        "timezone": {
            "description": "The timezone for all date input and display (e.g., \"America/Chicago\", from the TZ column at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).",
            "type": "string",
            "default": "America/Chicago"
        },
        "options": {
            "description": "Options for this course.",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "comment": {
                    "description": "Arbitrary comment for reference purposes.",
                    "anyOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}]
                },
                "useNewQuestionRenderer": {
                    "description": "Feature flag to enable the new question renderer.",
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "assessmentSets": {
            "description": "Assessment sets.",
            "type": "array",
            "items": {
                "description": "A single assessment set description.",
                "type": "object",
                "required": [
                    "abbreviation",
                    "name",
                    "heading",
                    "color"
                ],
                "properties": {
                    "comment": {
                        "description": "Arbitrary comment for reference purposes.",
                        "anyOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}]
                    },
                    "abbreviation": {
                        "description": "Abbreviation (preferably 1 to 3 characters), e.g., 'HW', 'Q', 'PQ', etc.",
                        "type": "string"
                    },
                    "name": {
                        "description": "Full singular name (preferably 1 to 3 words), e.g., 'Homework', 'Quiz', 'Practice Quiz'.",
                        "type": "string"
                    },
                    "heading": {
                        "description": "Plural heading for a group of assessments (preferably 1 to 3 words), e.g., 'Homeworks', 'Quizzes'.",
                        "type": "string"
                    },
                    "color": {
                        "$ref": "#/definitions/color"
                    }
                }
            }
        },
        "topics": {
            "description": "Question topics (visible to students).",
            "type": "array",
            "items": {
                "description": "A single assessment set description.",
                "type": "object",
                "required": [
                    "name",
                    "color"
                ],
                "properties": {
                    "comment": {
                        "description": "Arbitrary comment for reference purposes.",
                        "anyOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}]
                    },
                    "shortName": {
                        "description": "Short name (preferably 2 to 7 characters).",
                        "type": "string"
                    },
                    "name": {
                        "description": "Long descriptive name (preferably less than 10 words).",
                        "type": "string"
                    },
                    "color": {
                        "$ref": "#/definitions/color"
                    },
                    "description": {
                        "description": "Description of the topic.",
                        "type": "string"
                    }
                }
            }
        },
        "tags": {
            "description": "Question tags (not visible to students).",
            "type": "array",
            "items": {
                "description": "A single tag description.",
                "type": "object",
                "required": [
                    "name",
                    "color"
                ],
                "properties": {
                    "comment": {
                        "description": "Arbitrary comment for reference purposes.",
                        "anyOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}]
                    },
                    "shortName": {
                        "description": "Short name (preferably 2 to 7 characters).",
                        "type": "string"
                    },
                    "name": {
                        "description": "Long descriptive name (preferably less than 10 words).",
                        "type": "string"
                    },
                    "color": {
                        "$ref": "#/definitions/color"
                    },
                    "description": {
                        "description": "Description of the tag.",
                        "type": "string"
                    }
                }
            }
        }
    },
    "definitions": {
        "color": {
            "description": "A color name.",
            "enum": [
                "red1",
                "red2",
                "red3",
                "pink1",
                "pink2",
                "pink3",
                "purple1",
                "purple2",
                "purple3",
                "blue1",
                "blue2",
                "blue3",
                "turquoise1",
                "turquoise2",
                "turquoise3",
                "green1",
                "green2",
                "green3",
                "yellow1",
                "yellow2",
                "yellow3",
                "orange1",
                "orange2",
                "orange3",
                "brown1",
                "brown2",
                "brown3",
                "gray1",
                "gray2",
                "gray3"
            ]
        }
    }
}

=== PrairieLearn/PrairieLearn/templateCourse/infoCourse.json
{
  "uuid": "b7198b89-2dcd-405c-99c9-1df4aa9eaeec",
  "name": "TPL 101",
  "title": "Template Course",
  "options": {
    "useNewQuestionRenderer": true
  },
  "assessmentSets": [
    {
      "abbreviation": "HW",
      "name": "Homework",
      "heading": "Homeworks",
      "color": "green1"
    },
    {
      "abbreviation": "Q",
      "name": "Quiz",
      "heading": "Quizzes",
      "color": "red1"
    },
    {
      "abbreviation": "PQ",
      "name": "Practice Quiz",
      "heading": "Practice Quizzes",
      "color": "pink1"
    },
    {
      "abbreviation": "E",
      "name": "Exam",
      "heading": "Exams",
      "color": "brown1"
    },
    {
      "abbreviation": "PE",
      "name": "Practice Exam",
      "heading": "Practice Exams",
      "color": "yellow1"
    },
    {
      "abbreviation": "WS",
      "name": "Worksheet",
      "heading": "Worksheets",
      "color": "purple1"
    },
    {
      "abbreviation": "U",
      "name": "Unknown",
      "heading": "Unknown",
      "color": "red3"
    }
  ],
  "topics": [],
  "tags": [
    {
      "name": "numeric",
      "color": "brown1",
      "description": "The answer format is one or more numerical values."
    },
    {
      "name": "symbolic",
      "color": "blue1",
      "description": "The answer format is a symbolic expression."
    },
    {
      "name": "drawing",
      "color": "yellow1",
      "description": "The answer format requires drawing on a canvas to input a graphical representation of an answer."
    },
    {
      "name": "MC",
      "color": "green1",
      "description": "The answer format is choosing from a small finite set of answers."
    },
    {
      "name": "code",
      "color": "turquoise1",
      "description": "The answer format is a piece of code."
    },
    {
      "name": "multianswer",
      "color": "orange2",
      "description": "The question requires multiple answers, either as steps in a sequence or as separate questions."
    },
    {
      "name": "graph",
      "color": "purple1",
      "description": "The question tests reading information from a graph or drawing a graph."
    },
    {
      "name": "concept",
      "color": "pink1",
      "description": "The question tests conceptual understanding of a topic."
    },
    {
      "name": "calculate",
      "color": "green2",
      "description": "The questions tests performing a numerical calculation, with either a calculator or equivalent software."
    },
    {
      "name": "secret",
      "color": "red3",
      "description": "Only use this question on exams or quizzes that won't be released to students, so the question can be kept secret."
    },
    {
      "name": "nontest",
      "color": "green3",
      "description": "This question is not appropriate for use in a restricted testing environment, so only use it on homeworks or similar."
    }
  ]
}

=== PrairieLearn/PrairieLearn/apps/prairielearn/src/tests/testFileEditor/courseTemplate/infoCourse.json
{
    "uuid": "fd0bc861-b62a-4d24-bf1b-96053b8d3514",
    "name": "TEST 101",
    "title": "Test Course",
    "assessmentSets": [],
    "topics": [
        {
            "name": "Test",
            "color": "gray3",
            "description": "Feature examples"
        }
    ],
    "tags": [
        {
            "name": "tbretl",
            "color": "blue1",
            "description": "Question originally written by tbretl"
        }
    ]
}
