=== PrairieLearn/PrairieLearn/schemas/schemas/infoQuestion.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Question Info",
    "description": "Info files for questions.",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "uuid",
        "type",
        "title",
        "topic"
    ],
    "properties": {
        "uuid": {
            "description": "Unique identifier (UUID v4).",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "type": {
            "description": "Type of the question.",
            "enum": [
                "Calculation",
                "ShortAnswer",
                "MultipleChoice",
                "Checkbox",
                "File",
                "MultipleTrueFalse",
                "v3"
            ]
        },
        "title": {
            "description": "The title of the question (e.g., 'Addition of vectors in Cartesian coordinates').",
            "type": "string"
        },
        "topic": {
            "description": "The category of question (e.g., 'Vectors', 'Energy').",
            "type": "string"
        },
        "secondaryTopics": {
            "description": "Other topics also covered by the question (e.g., 'Vectors', 'Energy').",
            "type": "array",
            "items": {
                "description": "A single topic covered by the question.",
                "type": "string"
            }
        },
        "tags": {
            "description": "Extra tags associated with the question (e.g., 'Exam Only', 'Broken').",
            "type": "array",
            "items": {
                "description": "A tag associated with a question.",
                "type": "string"
            }
        },
        "thumbnail": {
            "description": "Filename and location associated with the question.",
            "type": "object",
            "required": [
                "filename",
                "location"
            ],
            "properties": {
                "filename": {
                    "description": "Filename of the thumbnail.",
                    "type": "string"
                },
                "location": {
                    "description": "Directory of the filename.",
                    "type": "string"
                }
            }
        },
        "clientFiles": {
            "description": "The list of question files accessible by the client (defaults to [\"client.js\"]).",
            "type": "array",
            "items": {
                "description": "A single file accessible by the client.",
                "type": "string"
            }
        },
        "clientTemplates": {
            "description": "List of client-accessible templates to render server-side.",
            "type": "array",
            "items": {
                "description": "A single template file accessible by the client.",
                "type": "string"
            }
        },
        "template": {
            "description": "The QID of a question that serves at the template for this question.",
            "type": "string"
        },
        "gradingMethod": {
            "description": "The grading method used for this question.",
            "enum": [
                "Internal",
                "External",
                "Manual"
            ]
        },
        "singleVariant": {
            "description": "Whether the question is not randomized and only generates a single variant (defaults to \"false\").",
            "type": "boolean"
        },
        "partialCredit": {
            "description": "Whether the question will give partial points for fractional scores (defaults to \"false\" for v2 questions and \"true\" for v3.).",
            "type": "boolean"
        },
        "options": {
            "description": "Options that define how the question will work, specific to the individual question type.",
            "type": "object"
        },
        "externalGradingOptions": {
            "description": "Options for externally graded questions.",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "image",
                "entrypoint"
            ],
            "properties": {
                "enabled": {
                    "description": "Whether the external grader is currently enabled. Useful if it is breaking, for example.",
                    "type": "boolean"
                },
                "image": {
                    "description": "The Docker image that will be used to grade this question. Should be specified as Dockerhub image.",
                    "type": "string"
                },
                "entrypoint": {
                    "description": "Program to run as the entrypoint to your grader. Must be runnable as 'chmod +x script && ./script'.",
                    "type": "string"
                },
                "serverFilesCourse": {
                    "description": "The list of files or directories that will be copied from course/externalGradingFiles/ to /grade/shared/",
                    "type": "array",
                    "items": {
                        "description": "A single file or directory that will be copied to the external grader.",
                        "type": "string"
                    }
                },
                "timeout": {
                    "description": "The number of seconds after which the grading job will timeout.",
                    "type": "integer"
                },
                "enableNetworking": {
                    "description": "Whether the grading containers should have network access. Access is disabled by default.",
                    "type": "boolean"
                }
            }
        },
        "dependencies": {
            "description": "The question's client-side dependencies.",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "coreStyles": {
                    "description": "The styles required by this question from /public/stylesheets.",
                    "type": "array",
                    "items": {
                        "description": "A .css file located in /public/stylesheets.",
                        "type": "string"
                    }
                },
                "coreScripts": {
                    "description": "The scripts required by this question from /public/javascripts.",
                    "type": "array",
                    "items": {
                        "description": "A .js file located in /public/javascripts.",
                        "type": "string"
                    }
                },
                "nodeModulesStyles": {
                    "description": "The styles required by this question from /node_modules.",
                    "type": "array",
                    "items": {
                        "description": "A .css file located in /node_modules.",
                        "type": "string"
                    }
                },
                "nodeModulesScripts": {
                    "description": "The scripts required by this question from /node_modules.",
                    "type": "array",
                    "items": {
                        "description": "A .js file located in /node_modules.",
                        "type": "string"
                    }
                },
                "clientFilesCourseStyles": {
                    "description": "The styles required by this question from clientFilesCourse.",
                    "type": "array",
                    "items": {
                        "description": "A .css file located in clientFilesCourse.",
                        "type": "string"
                    }
                },
                "clientFilesCourseScripts": {
                    "description": "The styles required by this question from clientFilesCourse.",
                    "type": "array",
                    "items": {
                        "description": "A .js file located in clientFilesCourse.",
                        "type": "string"
                    }
                },
                "clientFilesQuestionStyles": {
                    "description": "The styles required by this question from clientFilesQuestion.",
                    "type": "array",
                    "items": {
                        "description": "A .css file located in the clientFilesQuestion.",
                        "type": "string"
                    }
                },
                "clientFilesQuestionScripts": {
                    "description": "The scripts required by this question from clientFilesQuestion.",
                    "type": "array",
                    "items": {
                        "description": "A .js file located in the clientFilesQuestion.",
                        "type": "string"
                    }
                }
            }
        },
        "workspaceOptions": {
            "description": "Options for workspace questions.",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "image",
                "port",
                "home",
                "gradedFiles"
            ],
            "properties": {
                "image": {
                    "description": "The Docker image that will be used to serve this question. Should be specified as Dockerhub image.",
                    "type": "string"
                },
                "port": {
                    "description": "The port number used in the Docker image.",
                    "type": "integer"
                },
                "home": {
                    "description": "The home directory of the workspace container.",
                    "type": "string"
                },
                "args": {
                    "description": "Command line arguments to pass to the Docker.",
                    "type": "string"
                },
                "rewriteUrl": {
                    "description": "If true, the URL will be rewritten such that the workspace container will see all requests as originating from /.",
                    "type": "boolean"
                },
                "gradedFiles": {
                    "description": "The list of files or directories that will be copied for grading.",
                    "type": "array",
                    "items": {
                        "description": "A single file or directory that will be copied for grading.",
                        "type": "string"
                    }
                },
                "syncIgnore": {
                    "description": "The list of files or directories that will be excluded from sync.",
                    "type": "array",
                    "items": {
                        "description": "A single file or directory that will be excluded from sync.",
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== PrairieLearn/PrairieLearn/exampleCourse/questions/examplesFileEditor/info.json
{
    "uuid": "a5563b66-dfa1-4f69-a9d8-18a6ae1f6d7e",
    "title": "In browser file editor input with pl-file-editor",
    "topic": "Test",
    "tags": ["balamut2", "code", "v3"],
    "type": "v3",
    "singleVariant": true,
    "gradingMethod": "External",
    "externalGradingOptions": {
        "enabled": true,
        "image": "prairielearn/grader-python",
        "serverFilesCourse": ["python_autograder/"],
        "entrypoint": "/grade/serverFilesCourse/python_autograder/run.sh",
        "timeout": 20
    }
}

=== PrairieLearn/PrairieLearn/testCourse/questions/externalGrade/alpine/info.json
{
    "uuid": "3f3946e4-ebbd-452f-b1f3-756cb4f3a2f2",
    "title": "External Grading: Alpine Linux smoke test",
    "topic": "Autograder",
    "tags": ["code", "v3"],
    "type": "v3",
    "singleVariant": true,
    "gradingMethod": "External",
    "externalGradingOptions": {
        "enabled": true,
        "image": "alpine:latest",
        "entrypoint": "/grade/tests/grade.sh",
        "timeout": 10
    }
}

=== PrairieLearn/PrairieLearn/exampleCourse/questions/demoAutograderNumpy/info.json
{
    "uuid": "DF0FF186-DECC-448C-B23C-78D86A966E4C",
    "title": "Autograder demo: Using NumPy arrays",
    "topic": "Coding",
    "tags": [
        "v3",
        "sp20",
        "nnytko2",
        "short-coding"
    ],
    "type": "v3",
    "singleVariant": true,
    "gradingMethod": "External",
    "externalGradingOptions": {
        "enabled": true,
        "image": "prairielearn/grader-python",
        "entrypoint": "/python_autograder/run.sh",
        "timeout": 60
    }
}

=== PrairieLearn/PrairieLearn/testCourse/questions/v2checkbox/info.json
{
    "uuid": "b1533f99-f8e3-4495-b31c-d479096d40ae",
    "title": "Checkbox question (v2)",
    "topic": "Test",
    "tags": [],
    "type": "Checkbox",
    "options": {
      "text": "Check the TRUE statements.",
      "correctAnswers": [
        "True",
        "Correct",
        "Yes",
        "$1$"
      ],
      "incorrectAnswers": [
        "False",
        "Incorrect",
        "No",
        "$0$"
      ],
      "numberAnswers": 8,
      "minCorrectAnswers": 4,
      "maxCorrectAnswers": 4
    }
}

=== PrairieLearn/PrairieLearn/exampleCourse/questions/partialCredit4_v2/info.json
{
    "uuid": "7c0a303d-9b87-48a8-a968-b062210bae1a",
    "title": "Partial credit 4 (v2 without partial credit)",
    "topic": "Algebra",
    "tags": ["tbretl", "fa17", "tpl101", "v2"],
    "clientFiles": ["client.js", "question.html", "answer.html", "submission.html"],
    "type": "Calculation"
}

=== PrairieLearn/PrairieLearn/templateCourses/physicsEM/questions/OSUP/volume 2/Chapter 14/OSUPv2p14_68/info.json
{
            "uuid": "20899642-341f-3bd9-9f22-4546f1efbfe8",
            "title": "Switched LC Circuit",
            "topic": "Inductance",
            "tags": [
                "license:CC-BY-NC",
                "author:jake.bobowski@ubc.ca",
                "calculation"
              ],
              "type": "v3"
        }

=== PrairieLearn/PrairieLearn/exampleCourse/questions/demo/autograder/c/drawTriangle/info.json
{
    "uuid": "6e2f0457-5809-4f44-bc25-243f742e09c9",
    "title": "Autograder demo: Draw a triangle in C",
    "topic": "Autograder",
    "tags": [
        "code", "jonatan", "muchen", "c"
    ],
    "type": "v3",
    "singleVariant": true,
    "gradingMethod": "External",
    "externalGradingOptions": {
        "enabled": true,
        "image": "prairielearn/grader-c",
        "timeout": 100,
        "entrypoint": "python3 /grade/tests/test.py"
    }
}

=== PrairieLearn/PrairieLearn/exampleCourse/questions/demo/autograder/python/pandas/info.json
{
    "uuid": "F22EC735-A1EB-4816-AB4C-3DF908A62719",
    "title": "Autograder demo: Grading Pandas DataFrames",
    "topic": "Autograder",
    "tags": [
        "v3",
        "sp20",
        "nnytko2",
        "short-coding"
    ],
    "type": "v3",
    "singleVariant": true,
    "gradingMethod": "External",
    "externalGradingOptions": {
        "enabled": true,
        "image": "prairielearn/grader-python",
        "entrypoint": "/python_autograder/run.sh",
        "timeout": 60
    }
}
