=== PrairieLearn/PrairieLearn/backend/schemas/questionInfo.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Question Info",
    "description": "Info files for questions.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "type": {
            "description": "Type of the test.",
            "enum": ["Calculation", "MultipleChoice", "Checkbox", "File", "MultipleTrueFalse"],
            "required": true
        },
        "title": {
            "description": "The title of the question (e.g., 'Addition of vectors in Cartesian coordinates').",
            "type": "string",
            "required": true
        },
        "topic": {
            "description": "The category of question (e.g., 'Vectors', 'Energy').",
            "type": "string",
            "required": true
        },
        "tags": {
            "description": "Extra tags associated with the question (e.g., 'Cartesian', 'graphics').",
            "type": "array",
            "items": {
                "description": "An arbitrary tag associated with a question.",
                "type": "string"
            }
        },
        "clientFiles": {
            "description": "The list of question files accessible by the client (defaults to [\"client.js\"]).",
            "type": "array",
            "items": {
                "description": "A single file accessible by the client.",
                "type": "string"
            }
        },
        "template": {
            "description": "The QID of a question that serves at the template for this question.",
            "type": "string"
        },
        "options": {
            "description": "Options that define how the question will work, specific to the individual question type.",
            "type": "object"
        }
    }
}

=== PrairieLearn/PrairieLearn/v2/exampleCourse/Sp15questions/fossilFuelsCheckbox/info.json
{
    "title": "Advantages of fossil fuels (checkbox)",
    "topic": "Energy",
    "tags": ["Comparative"],
    "clientFiles": ["client.js", "power-station.jpg"],
    "type": "Checkbox",
    "options": {
        "text": "Which of the following are advantages of fossil fuels relative to renewable energy sources? Select all that apply.<img src=\"<% print(questionFile(\"power-station.jpg\")) %>\" width=\"400px\" class=\"img-responsive center-block\" />",
        "correctAnswers": [
            "Cheap",
            "High energy density",
            "Provide energy on demand"            
        ],
        "incorrectAnswers": [
            "Non-polluting",
            "Low energy density",
            "Low production of carbon dioxide",
            "High production of carbon dioxide",
            "Secure",
            "Sustainable",
            "Low energy return"
        ],
        "numberAnswers": 5,
        "minCorrectAnswers": 1,
        "maxCorrectAnswers": 3
    }
}
